import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Pay from "../Components/pay.js"
import StepContextProvider from './../Contexts/StepContext';
import Main from './../Layout/main.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fincra Pay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Main>
        <StepContextProvider>
        <Pay />
         </StepContextProvider>
         </Main>
      </main>
    </div>
  )
}
